name: eventifyQr
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences_web: ^2.4.2
  animated_text_kit: ^4.2.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  shared_preferences: ^2.2.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
